name: test

on:
  pull_request: { }
  push:
    branches:
      - master

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with: { go-version: 1.17 }
      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - name: Install task
        uses: arduino/setup-task@v1
      - name: Run tests
        run: task test
      - name: Run golangci-lint
        run: task lint
