name: test

on:
  pull_request: { }
  push:
    branches:
      - master

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v3
        with: { go-version: 1.17 }
      - name: Install task
        uses: arduino/setup-task@v1
      - name: Run tests
        run: task test
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with: { version: latest, skip-pkg-cache: true, skip-build-cache: true }
